/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.1, using .NET Server 4.2.0 template (version 4)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**
**     Generated by Kraftcoding <info@Kraftcoding.com>
** </auto-generated>
**
** Copyright (c) 2006-2025 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://Kraftcoding.org/TemperatureUAServer/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Created: 21.09.2025
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnifiedAutomation.UaBase;
using UnifiedAutomation.UaServer;

namespace Kraftcoding.TemperatureUAServer
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // There is no license file configured in UaModeler.
                // After you have added a license file to the project you can add the license with the following
                // line of code.
                // ApplicationLicenseManager.AddProcessLicenses(System.Reflection.Assembly.GetExecutingAssembly(), "License.lic");


                // Start the server.
                ServerManager server = new TemperatureUAServerServerManager();
                var application = ApplicationInstance.Default;
                application.AutoCreateCertificate = true;

                application.UntrustedCertificate += (s, e) =>
                {
                    if (e.ValidationError.CodeBits == StatusCodes.BadCertificateUntrusted)
                    {
                        Console.WriteLine($"Untrusted certificate {e.Certificate.SubjectName}");
                        Console.WriteLine($"Move certificate {e.Certificate.CommonName} [{e.Certificate.Thumbprint}].der to {e.TrustedStore.StorePath} to trust it.");
                    }
                    else
                    {
                        Console.WriteLine($"Validation error {e.ValidationError} for certificate {e.Certificate.SubjectName}");
                    }
                };

                application.Start(server, null, server);

                Console.WriteLine("Endpoint URL: opc.tcp://localhost:48030");
                // Block until the server exits.
                Console.WriteLine("Press <enter> to exit the program.");
                Console.ReadLine();
                // Stop the server.
                server.Stop();
            }
            catch (Exception e)
            {
                Console.WriteLine("ERROR: {0}", e.Message);
                Console.WriteLine("Press <enter> to exit the program.");
                Console.ReadLine();
            }
        }

    }
}

